services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next  # This will use a named volume for .next
    environment:
      - NODE_ENV=development
    command: npm run dev